create table restaurante (

		id int8 generated by default as identity, 
		nome varchar(100) not null, 
		taxa_frete numeric(19, 2) not null, 
		cozinha_id int8 not null, 
		
		data_atualizacao timestamp not null, 
		data_cadastro timestamp not null, 
		endereco_cidade_id int8, 
		endereco_bairro varchar(120), 
		endereco_cep varchar(20), 
		endereco_complemento varchar(200), 
		endereco_logradouro varchar(200), 
		endereco_numero varchar(20), 
		primary key (id)
		
		)
		
		

