create table pedido (

		id int8 generated by default as identity, 
		data_cancelamento timestamp, 
		data_confirmacao timestamp, 
		data_criacao timestamp, 
		data_entrega timestamp, 
		
		endereco_bairro varchar(255), 
		endereco_cep varchar(255), 
		endereco_complemento varchar(255), 
		endereco_logradouro varchar(255), 
		endereco_numero varchar(255), 
		endereco_cidade_id int8, 
		
		status varchar(10) not null, 
		subtotal numeric(19, 2), 
		taxa_frete numeric(19, 2), 
		valor_total numeric(19, 2), 
		usuario_cliente_id int8 not null, 
		forma_pagamento_id int8 not null, 
		restaurante_id int8 not null, 
		
		primary key (id),
		
		
		constraint Fk_pedido_usuario foreign key (usuario_cliente_id) references usuario,
		constraint Fk_pedido_cidade foreign key (endereco_cidade_id) references cidade,
		constraint Fk_pedido_formapagamento foreign key (forma_pagamento_id) references forma_pagamento,
		constraint Fk_pedido_restaurante foreign key (restaurante_id) references restaurante
		
		
		)
